# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
fabric_version=0.141.6+1.21.11

# Mod Properties
mod_version=1.0.0
maven_group=net.arcanetablet
archives_base_name=arcanetablet

# Java Runtime Configuration
org.gradle.java.home=C:/Program Files/Microsoft/jdk-21.0.12.8-hotspot
