modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/shufunk-dev/arcanetablet"
logoFile="icon.png"
credits="Created by ${mod_authors}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.arcanetablet]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcanetablet]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
